# Generated by Django 3.0.1 on 2020-01-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
